### ISSUE TITLE
Make members of the github org public, add everyone to org

### ISSUE THREAD

**Issue by RuyueJ** [kaizendorks/kaizendorks.github.io#8]

**Comment by iorubs** [comment]
This needs to be done by each individual user here: https://github.com/orgs/kaizendorks/people, simply change Private to Public beside your name.

In relation to the second part, it's kinda hard to add everyone in one go because we don't know their usernames, so this will be done on a person by person basis.

**Comment by iorubs** [comment]
Nothing else to do here so closing the issue.

**Comment by iorubs** [comment]
Nothing else to do here so closing the issue.
